### ISSUE TITLE
The library com.google.android.gms:play-services-auth-base is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 15.1.0

### ISSUE THREAD

**Issue by firashamila33** [dandar3/android-google-play-services-auth-base#1]
Hello , my problem is that google-sign-in is requiring this library 

```
implementation(project(":react-native-google-signin")){
         exclude group: "com.google.android.gms" // very important
     }
     implementation 'com.google.android.gms:play-services-auth:15.0.1'

```
But I get this error ,, what can I do ?? 
I tried lots of tricks every where but no solution

`The library com.google.android.gms:play-services-auth-base is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 15.1.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.`

**Comment by dandar3** [comment]
@firashamila33 
The message is trying to help by running `./gradlew :app:dependencies`. That will build you a nice dependency tree that will tell you which dependecy requires `play-services-auth-base:15.1.0`

Otherwise you could try to up yours to 15.1.0 to match it, or simply remove yours as it brought into your project by another dependency.
`  implementation 'com.google.android.gms:play-services-auth:15.1.0'`

**Comment by firashamila33** [comment]
could not update  manually to com.google.android.gms:play-services-auth:15.1.0 .
But **I solved the problem** ,, in /myapp/build.gradle  I was using a classpath dependencies higher then  react-native-google-signin require . 
thank you @dandar3
